### ISSUE TITLE
Unable to use the panel

### ISSUE THREAD

**Issue by espositoandrea** [barckley75/Blender_Neural_Network#2]
Hi,

I've stumbled upon this repository while searching for a way of representing a NN in Blender. I've tried it, using Blender 2.93.3 and Animation Nodes. Everything seems fine, but I'm not able to customise the network due to the following errors:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/23329364/132877834-efcd3d78-97b3-4898-b2c9-1244f06a3d57.png">

Any idea on how I can solve these issues?
Thanks in advance.

**Comment by barckley75** [comment]
Hi,
which version of animation nodes are you using?

**Comment by espositoandrea** [comment]
Hi, thanks for the response.
I'm using version 2.2.2, as it is compatible with the version of blender I'm using.

**Comment by barckley75** [comment]
Try to open Blender via terminal. You should be able to read the problems and post it here please.
Check also (if you have windows, this is the path C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages) if there is numpy.

**Comment by espositoandrea** [comment]
Hi,
I have numpy installed in the Blender's interpreter. Trying to open the provided example file using the command line yields the following:

```
Read prefs: /Users/andrea/Library/Application Support/Blender/2.93/config/userpref.blend
Registered Animation Nodes
Read blend: /Users/andrea/Downloads/Blender_Neural_Network-main/artificialNeuralNetwork.blend
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'Invoke Subprogram.002'
    Name: 'Numpy Array'
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'From Numpy'
    Name: 'Numpy Array'
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'Script'
    Name: 'Numpy Array'
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'Create List'
    Name: 'Element'
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'Create List'
    Name: 'List (1)'
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'Get List Element'
    Name: 'List'
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'Get List Element'
    Name: 'Fallback'
WARNING: socket removed
    Tree: 'Artificial Neural Network'
    Node: 'Get List Element'
    Name: 'Element'
Traceback (most recent call last):
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/update_file.py", line 22, in updateFile
    node._refresh()
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/nodes/base_node.py", line 215, in _refresh
    self._create()
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/nodes/base_node.py", line 222, in _create
    self.create()
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/nodes/list/get_list_element.py", line 32, in create
    self.newInput(ListTypeSelectorSocket(
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/nodes/base_node.py", line 311, in newInput
    socket = template.createInput(self)
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/socket_templates/base.py", line 3, in createInput
    return self.create(node, node.inputs)
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/socket_templates/list_type_selector.py", line 39, in create
    dataType = self.toType(getattrRecursive(node, self.propertyName))
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/sockets/info.py", line 138, in toListDataType
    return _socketInfo.listDataType[input]
KeyError: 'Numpy Array'
Python: Traceback (most recent call last):
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/nodes/base_node.py", line 188, in draw_label
    return self.drawLabel()
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/nodes/list/create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/sockets/info.py", line 138, in toListDataType
    return _socketInfo.listDataType[input]
KeyError: 'Numpy Array'
```

Then it repeats too many times to count the following error (like the last few lines of the above with the addition of the "location" error):

```
location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/base_types/nodes/base_node.py", line 188, in draw_label
    return self.drawLabel()
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/nodes/list/create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
  File "/Users/andrea/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/sockets/info.py", line 138, in toListDataType
    return _socketInfo.listDataType[input]
KeyError: 'Numpy Array'
```

Any idea on the reason? May it be a buggy Animation Nodes version, or am I missing something? Thanks for your help.

**Comment by barckley75** [comment]
Apparently the version from the official page it doesn't work. Try this version of animation nodes from Graphicall:
[Animation Nodes From Graphicall](https://blender.community/c/graphicall/0hbbbc)
I just installed everything from scratch and it works.
You need to remove the old animation nodes version before install the new one.

**Comment by espositoandrea** [comment]
Hi, sorry for the delay.

I'm unable to test your solution as I only have access to either a GNU/Linux machine or an ARM MacOS. I'll have to wait for GraphicAll to release a build for either OSs. But I think we can nonetheless close the issue as you said that everything works!

Thanks again!
